//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Atelier_Couture.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplementMesurefemme
    {
        public int idClient { get; set; }
        public Nullable<double> dessousPoit { get; set; }
        public Nullable<double> creteslliaque { get; set; }
        public Nullable<double> LDos { get; set; }
    }
}
