//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Atelier_Couture.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int idLogin { get; set; }
        public string utilisateur { get; set; }
        public string mdpasse { get; set; }
    }
}
