//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Atelier_Couture.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesure
    {
        public int idClient { get; set; }
        public Nullable<double> tete { get; set; }
        public Nullable<double> cou { get; set; }
        public Nullable<double> epaule { get; set; }
        public Nullable<double> LBras { get; set; }
        public Nullable<double> poitrine { get; set; }
        public Nullable<double> hanches { get; set; }
        public Nullable<double> LCorps { get; set; }
        public Nullable<double> cuisse { get; set; }
        public Nullable<double> genou { get; set; }
        public Nullable<double> mollet { get; set; }
        public Nullable<double> cheville { get; set; }
        public Nullable<double> biceps { get; set; }
        public Nullable<double> coude { get; set; }
        public Nullable<double> avantBras { get; set; }
        public Nullable<double> poignetCoude { get; set; }
        public Nullable<double> entreJambe { get; set; }
        public Nullable<double> coutureExt { get; set; }
        public Nullable<double> hTotale { get; set; }
    }
}
