//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Atelier_Couture.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public int idPers { get; set; }
        public string NomPers { get; set; }
        public string PrenomPers { get; set; }
        public string AdressPers { get; set; }
        public string TelPers { get; set; }
        public string EmailPers { get; set; }
    }
}
